spring:
  application:
    name: finalTest_eazyzero
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://server.starj.kro.kr:3306/honeybadger1?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/mission?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ''
server:
  port: 8080